### ISSUE TITLE
Please consider updating your cookbooks on community.opscode.com

### ISSUE THREAD

**Issue by posita** [jellybob/kitchen#6]
It looks like [your statsd cookbook](http://community.opscode.com/cookbooks/statsd) hasn't been updated on community.opscode.com since its initial release. I'm guessing users could benefit from some of the changes that have happened since then....

**Comment by jellybob** [comment]
I'll be honest, I've not used this cookbook in several months after changing how we manage metrics in our internal infrastructure. How would you feel about taking it over, since you seem to be a lot more motivated to keep things going?

**Comment by posita** [comment]
I'll consider it (in which case I'll fork it, publish, and let you know), but to be honest, I kind of hacked up my own stuff that fit the bill (for now). When it breaks, I'll probably be back.... ;o)

**Comment by jellybob** [comment]
No problem!
